main: main.cpp
		g++ -g -Wall -Wextra g_obj/vec.cpp g_obj/line.cpp g_obj/plane.cpp g_obj/triangle.cpp geom.cpp main.cpp
test: tst.cpp
		g++ -g -Wall -Wextra g_obj/vec.cpp g_obj/line.cpp g_obj/plane.cpp g_obj/triangle.cpp geom.cpp tst.cpp
